### ISSUE TITLE
Coupon Expiry

### ISSUE THREAD

**Issue by aliceseaborn** [sidd-harth/fluxcd-tracker#3]
Hey there,

I have a KillerCoda subscription as well as a Udemy subscription but your FluxCD course is still showing up as ~$85 ([Udemy - FluxCD GitOps Flux](https://www.udemy.com/course/gitops-flux)). I'd really like to take your Udemy course but I don't think I can justify the expense for a single course offering. I know you used to offer coupons such as `GITOPS-FLUX-APR-2023` but that coupon no longer works. Could you publish a new one?

Thanks!
~alice

**Comment by sidd-harth** [comment]
Hi, I'm unsure why the price is so high. You could use this coupon to check it out.

https://www.udemy.com/course/gitops-flux/?couponCode=BDEE4B27282F4C01BD0E

Regards,
Siddharth

**Comment by sidd-harth** [comment]
Hi, I'm unsure why the price is so high. You could use this coupon to check
it out.

https://www.udemy.com/course/gitops-flux/?couponCode=BDEE4B27282F4C01BD0E

Regards,
Siddharth

**Comment by aliceseaborn** [comment]
Thank you! Udemy does silly things with their course prices.
